## 02 scikit-learn 中的 kNN 

In [16]:
import numpy as np
import matplotlib.pyplot as plt

In [17]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

```python
def kNN_classify(k, X_train, y_train, x):

    assert 1 <= k <= X_train.shape[0], "k must be valid"
    assert X_train.shape[0] == y_train.shape[0], \
        "the size of X_train must equal to the size of y_train"
   # x 是传入的被预测的数据
   assert X_train.shape[1] == x.shape[0], \
        "the feature number of x must be equal to X_train"

    distances = [sqrt(np.sum((x_train - x)**2)) for x_train in X_train]
    nearest = np.argsort(distances)

    topK_y = [y_train[i] for i in nearest[:k]]
    votes = Counter(topK_y)

    return votes.most_common(1)[0][0]


```

In [18]:
%run kNN_function/kNN.py

In [19]:
predict_y = kNN_classify(6, X_train, y_train, x)

In [20]:
predict_y

1

### 模型训练的过程
![IMAGE](https://farm2.staticflickr.com/1741/42694985981_e87d81d91f_o.png)

#### 第一步：味入数据
* 数据本身
* 模型的标签

#### 第二部：fit 也就是模型的训练（拟合）

#### 第三部：得到预测结果
======

* K 近邻算法是非常特殊的，可以被认为是没有模型的算法
* 为了和其他算法统一，可以认为训练数据集就是模型本身

### 使用scikit-learn中的kNN

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [31]:
# Scikit-learn 是面向对象包装，所以第一步我们需要创建一个实例
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [32]:
kNN_classifier.fit(X_train, y_train) # 返回值是他自己

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [35]:
x # ❤️ 当只有一个数据的时候，很容易出错，我们最好把他转化成矩阵的形式

array([ 8.09360732,  3.36573151])

In [36]:
kNN_classifier.predict(xakNN_classifier.predict(x)

SyntaxError: unexpected EOF while parsing (<ipython-input-36-e3b5d9f59a4e>, line 1)

In [38]:
X_predict = x.reshape(1, -1)

In [39]:
X_predict

array([[ 8.09360732,  3.36573151]])

In [40]:
kNN_classifier.predict(X_predict)

array([1])

In [41]:
y_predict = kNN_classifier.predict(X_predict) # 保存结果

In [42]:
y_predict[0] # 从结果的数组中提取最终的结果

1

### 重新整理我们的kNN的代码
我们模仿 Sklearn 的方法，重新整理我们自己的代码

代码参见 [这里](kNN/KNN.py)
```python
class KNNClassifier:

    def __init__(self, k):
        """初始化kNN分类器"""
        assert k >= 1, "k must be valid"
        self.k = k
        self._X_train = None # 这个是私有的成员变量
        self._y_train = None

    def fit(self, X_train, y_train):
        """根据训练数据集X_train和y_train训练kNN分类器"""
        assert X_train.shape[0] == y_train.shape[0], \
            "the size of X_train must be equal to the size of y_train"
        assert self.k <= X_train.shape[0], \
            "the size of X_train must be at least k."

        self._X_train = X_train
        self._y_train = y_train
        return self # ❤️ fit 函数要返回自身

    def predict(self, X_predict):
        """给定待预测数据集X_predict，返回表示X_predict的结果向量"""
        assert self._X_train is not None and self._y_train is not None, \
                "must fit before predict!"
        assert X_predict.shape[1] == self._X_train.shape[1], \
                "the feature number of X_predict must be equal to X_train"

           # ❤️ 对数组中的每一个 x 进行单独处理
        y_predict = [self._predict(x) for x in X_predict]
        return np.array(y_predict)
        #❤️ 模仿 Sklearn 把结果封装成 np.array()

    def _predict(self, x):
        """给定单个待预测数据x，返回x的预测结果值"""
        assert x.shape[0] == self._X_train.shape[1], \
            "the feature number of x must be equal to X_train"

        distances = [sqrt(np.sum((x_train - x) ** 2))
                     for x_train in self._X_train]
        nearest = np.argsort(distances)

        topK_y = [self._y_train[i] for i in nearest[:self.k]]
        votes = Counter(topK_y)

        return votes.most_common(1)[0][0]


    # represent 函数
    def __repr__(self):
        return "KNN(k=%d)" % self.k
```

In [44]:
%run kNN/kNN.py

In [45]:
knn_clf = KNNClassifier(3)

In [46]:
knn_clf.fit(X_train, y_train)

KNN(k=3)

In [47]:
y_predict = knn_clf.predict(X_predict)

In [48]:
y_predict

array([1])

In [49]:
y_predict[0]

1

In [50]:
print(knn_clf)

KNN(k=3)
