## 06 ``numpy.array`` 合并和分割

In [19]:
import numpy as np

### ``numpy.array`` 的合并

In [20]:
x = np.array([1, 2, 3]) # 一维向量的拼接
y = np.array([3, 2, 1])

In [21]:
np.concatenate([x, y]) # ❤️ 要传入一个 list

array([1, 2, 3, 3, 2, 1])

In [22]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z]) 

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [23]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
z

array([666, 666, 666])

In [28]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [29]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

注意，现在 z 的形状变了吗? 没有变。

In [30]:
z

array([666, 666, 666])

通常我们讲拼接的结果返回到一个新的元素里
result = np.concatente([A,Z.reshape(1,-1))

#### vstack 与 hstack
numpy 提供了两种简单的拼接方式，并且更加智能**可以对矩阵的维度容错**

In [31]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [32]:
B = np.full((2,2), 100)

In [33]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

虽然可以智能改变维度，但是不可以传入非法的矩阵

In [34]:
print(A)
print(z)

[[1 2 3]
 [4 5 6]]
[666 666 666]


In [35]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### ``numpy.array`` 的分割

In [36]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

split有两个参数
* 第一个传入的列表
* 第二个是分割点，分割点可以是多个，所以可以用列表的方式。
这里[3,7]把 x 分割成了三段
1. x1 = x[:3]
2. x2 = x[3:7]
3. x3 = x[7:]

In [37]:
x1, x2, x3 = np.split(x, [3, 7])

In [38]:
x1

array([0, 1, 2])

In [39]:
x2

array([3, 4, 5, 6])

In [40]:
x3

array([7, 8, 9])

切割成两段，仍然要穿入一个list

In [41]:
x1, x2 = np.split(x, [5])

In [42]:
x1

array([0, 1, 2, 3, 4])

In [43]:
x2

array([5, 6, 7, 8, 9])

二维数组的切割

In [44]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
A1, A2 = np.split(A, [2])

In [46]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
A1, A2 = np.split(A, [2], axis=1)

In [49]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [50]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [51]:
upper, lower = np.vsplit(A, [2])

In [52]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
left, right = np.hsplit(A, [2])

In [55]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [56]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [57]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 分割的具体应用
data 的前3列是 feature，最后一列是 label，所以我们要对他们进行分割

In [58]:
X,  label = np.hsplit(data, [-1])

In [59]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [60]:
label

array([[ 3],
       [ 7],
       [11],
       [15]])

有些时候我们要把 label 转化成一个 vector，也就是一个一维的向量

In [61]:
label[:, 0] # 抽出所有行，然后抽出1列

array([ 3,  7, 11, 15])