## 07 ``numpy.array`` 中的运算

给定一个数组，让数组中每一个数乘以2

In [11]:
n = 10
L = [i for i in range(n)]

In [12]:
2 * L # 原生的 python 是把 list 复制了一遍，并不是*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
A = []
for e in L:
    A.append(2*e)

In [14]:
n = 1000000
L = [i for i in range(n)]

In [15]:
%%time
A = []
for e in L:
    A.append(2*e)

CPU times: user 162 ms, sys: 28.9 ms, total: 191 ms
Wall time: 194 ms


In [16]:
%%time
A = [2*e for e in L]

CPU times: user 87.7 ms, sys: 28.3 ms, total: 116 ms
Wall time: 114 ms


> comprehension 要快于 for loop

In [17]:
import numpy as np
L = np.arange(n)

In [18]:
%%time
A = np.array(2*e for e in L)

CPU times: user 16.2 ms, sys: 8.53 ms, total: 24.7 ms
Wall time: 25.9 ms


In [19]:
%%time
A = 2 * L

CPU times: user 3.57 ms, sys: 4.83 ms, total: 8.41 ms
Wall time: 6.52 ms


In [20]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### NumPy’s UFuncs (Universal Functions)

In [21]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [23]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [25]:
X / 2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5]])

In [26]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [27]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [28]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [29]:
1 / X

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ],
       [ 0.09090909,  0.08333333,  0.07692308,  0.07142857,  0.06666667]])

In [30]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [32]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [33]:
np.tan(X)

array([[  1.55740772e+00,  -2.18503986e+00,  -1.42546543e-01,
          1.15782128e+00,  -3.38051501e+00],
       [ -2.91006191e-01,   8.71447983e-01,  -6.79971146e+00,
         -4.52315659e-01,   6.48360827e-01],
       [ -2.25950846e+02,  -6.35859929e-01,   4.63021133e-01,
          7.24460662e+00,  -8.55993401e-01]])

In [34]:
np.arctan(X)

array([[ 0.78539816,  1.10714872,  1.24904577,  1.32581766,  1.37340077],
       [ 1.40564765,  1.42889927,  1.44644133,  1.46013911,  1.47112767],
       [ 1.48013644,  1.48765509,  1.49402444,  1.49948886,  1.50422816]])

In [35]:
np.exp(X)

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
          5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
          8.10308393e+03,   2.20264658e+04],
       [  5.98741417e+04,   1.62754791e+05,   4.42413392e+05,
          1.20260428e+06,   3.26901737e+06]])

In [36]:
np.exp2(X)

array([[  2.00000000e+00,   4.00000000e+00,   8.00000000e+00,
          1.60000000e+01,   3.20000000e+01],
       [  6.40000000e+01,   1.28000000e+02,   2.56000000e+02,
          5.12000000e+02,   1.02400000e+03],
       [  2.04800000e+03,   4.09600000e+03,   8.19200000e+03,
          1.63840000e+04,   3.27680000e+04]])

In [37]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [38]:
np.log(X)

array([[ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791],
       [ 1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509],
       [ 2.39789527,  2.48490665,  2.56494936,  2.63905733,  2.7080502 ]])

In [39]:
np.log2(X)

array([[ 0.        ,  1.        ,  1.5849625 ,  2.        ,  2.32192809],
       [ 2.5849625 ,  2.80735492,  3.        ,  3.169925  ,  3.32192809],
       [ 3.45943162,  3.5849625 ,  3.70043972,  3.80735492,  3.9068906 ]])

In [40]:
np.log10(X)

array([[ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ],
       [ 0.77815125,  0.84509804,  0.90308999,  0.95424251,  1.        ],
       [ 1.04139269,  1.07918125,  1.11394335,  1.14612804,  1.17609126]])

In [41]:
X # 这里 X 并没有发生变化

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### 矩阵运算

In [42]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [43]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [44]:
A + B

array([[10, 11],
       [12, 13]])

In [45]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [46]:
A * B # 对应元素想成，并不是标准的矩阵想成

array([[ 0, 10],
       [20, 30]])

In [47]:
np.multiply(A,B) 

array([[ 0, 10],
       [20, 30]])

In [48]:
A.dot(B) # 标准的矩阵乘法

array([[10, 10],
       [50, 50]])

In [49]:
A.T

array([[0, 2],
       [1, 3]])

In [50]:
C = np.full((3, 3), 666)

In [51]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

#### 向量和矩阵的运算

#### 加法

In [52]:
v = np.array([1, 2])
print(v)
print(A)

[1 2]
[[0 1]
 [2 3]]


In [53]:
v + A

array([[1, 3],
       [3, 5]])

``v + A`` 是可以的，但是在这个课程中，我们不研究其中的计算法则。有兴趣的同学可以查询资料自学``numpy.array``的broadcast

In [54]:
np.vstack([v] * A.shape[0]) # A.shape[0] A 的行数

array([[1, 2],
       [1, 2]])

In [55]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [56]:
np.tile(v, (2, 1)) # 行方向上堆叠两次，列不动

array([[1, 2],
       [1, 2]])

In [57]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [58]:
np.tile(v, (2, 2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

#### 乘法

In [59]:
v

array([1, 2])

In [60]:
A

array([[0, 1],
       [2, 3]])

In [61]:
v * A

array([[0, 2],
       [2, 6]])

In [62]:
v.dot(A)

array([4, 7])

In [63]:
A.dot(v) # v 作为右边的矩阵，自动从一个行向量，变为了一个列向量

array([2, 8])

### 矩阵的逆

In [64]:
np.linalg.inv(A) # 逆矩阵需要调用线性代数的包

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [65]:
invA = np.linalg.inv(A)

In [66]:
A.dot(invA)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [67]:
invA.dot(A)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [68]:
X = np.arange(16).reshape((2, 8))

In [69]:
invX = np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

#### 矩阵的伪逆

In [70]:
pinvX = np.linalg.pinv(X) # p 是 psedu 的简写
pinvX

array([[ -1.35416667e-01,   5.20833333e-02],
       [ -1.01190476e-01,   4.16666667e-02],
       [ -6.69642857e-02,   3.12500000e-02],
       [ -3.27380952e-02,   2.08333333e-02],
       [  1.48809524e-03,   1.04166667e-02],
       [  3.57142857e-02,  -9.65081753e-18],
       [  6.99404762e-02,  -1.04166667e-02],
       [  1.04166667e-01,  -2.08333333e-02]])

In [71]:
X.dot(pinvX)

array([[  1.00000000e+00,  -2.42861287e-16],
       [ -5.41233725e-16,   1.00000000e+00]])

矩阵的伪逆又被称为“广义逆矩阵”，有兴趣的同学可以翻看线性教材课本查看更多额广义逆矩阵相关的性质。中文wiki链接: [https://zh.wikipedia.org/wiki/%E5%B9%BF%E4%B9%89%E9%80%86%E9%98%B5](https://zh.wikipedia.org/wiki/%E5%B9%BF%E4%B9%89%E9%80%86%E9%98%B5)