## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
np.random.seed(666)
x = np.random.normal(0, 1, 1000000)

### 索引

In [3]:
np.argmin(x) # 最小值所在的索引

971892

In [4]:
x[971892]

-4.7697870800016089

In [5]:
np.min(x)

-4.7697870800016089

In [6]:
np.argmax(x) # 最大值所在的索引

717667

In [7]:
x[717667]

4.9278013550247239

In [8]:
np.max(x)

4.9278013550247239

### 排序和使用索引

In [13]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
np.random.shuffle(x)
x

array([ 9,  8,  3, 14, 15,  6,  2, 12,  4, 13,  5,  7, 10,  1,  0, 11])

In [15]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
x.sort() # 在 x 本身上调用sort，才可以进行排序

In [21]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
X = np.random.randint(10, size=(4,4))
X

array([[6, 0, 6, 6],
       [8, 7, 5, 6],
       [4, 6, 5, 4],
       [8, 5, 2, 7]])

In [23]:
np.sort(X, axis=0) # 沿着行方向进行排序，结果是列的方向变成有序

array([[4, 0, 2, 4],
       [6, 5, 5, 6],
       [8, 6, 5, 6],
       [8, 7, 6, 7]])

In [25]:
np.sort(X, axis=1) # 沿着列方向进行排序，也就是行变成有序

array([[0, 6, 6, 6],
       [5, 6, 7, 8],
       [4, 4, 5, 6],
       [2, 5, 7, 8]])

#### 使用索引

In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
np.random.seed(666)
np.random.shuffle(x)

In [28]:
x = np.array([ 3.14, 14.2, 10.33, 12.3,  8,  6,  9,  7.4,  4, 15,  2,  5, 11, 13,  1,  0])

In [29]:
np.argsort(x) # 最小的数字在是0，他的索引是15

array([15, 14, 10,  0,  8, 11,  5,  7,  4,  6,  2, 12,  3, 13,  1,  9])

In [30]:
help(np.partition)

Help on function partition in module numpy.core.fromnumeric:

partition(a, kth, axis=-1, kind='introselect', order=None)
    Return a partitioned copy of an array.
    
    Creates a copy of the array with its elements rearranged in such a
    way that the value of the element in k-th position is in the
    position it would be in a sorted array. All elements smaller than
    the k-th element are moved before this element and all equal or
    greater are moved behind it. The ordering of the elements in the two
    partitions is undefined.
    
    .. versionadded:: 1.8.0
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    kth : int or sequence of ints
        Element index to partition by. The k-th value of the element
        will be in its final sorted position and all smaller elements
        will be moved before it and all equal or greater elements behind
        it. The order all elements in the partitions is undefined. If
        provided with a 

In [33]:
np.partition(x, 3) # 3 前面的数字都比3小，但注意不是有序的

array([  2.  ,   0.  ,   1.  ,   3.14,   8.  ,   6.  ,   9.  ,  14.2 ,
         4.  ,  15.  ,  12.3 ,   5.  ,  11.  ,  13.  ,  10.33,   7.4 ])

In [34]:
np.partition(x, 3.14) # 3 前面的数字都比3小，但注意不是有序的

TypeError: Partition index must be integer

In [35]:
np.argpartition(x, 3)

array([10, 15, 14,  0,  4,  5,  6,  1,  8,  9,  3, 11, 12, 13,  2,  7])

In [36]:
X

array([[6, 0, 6, 6],
       [8, 7, 5, 6],
       [4, 6, 5, 4],
       [8, 5, 2, 7]])

In [37]:
np.argsort(X, axis=1)

array([[1, 0, 2, 3],
       [2, 3, 1, 0],
       [0, 3, 2, 1],
       [2, 1, 3, 0]])

In [38]:
np.argpartition(X, 2, axis=1)

array([[1, 0, 2, 3],
       [2, 3, 1, 0],
       [0, 3, 2, 1],
       [2, 1, 3, 0]])