## 05 ``numpy.array`` 基本操作

In [59]:
import numpy as np
np.random.seed(0)

x = np.arange(10)

In [60]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
X = np.arange(15).reshape((3, 5))

In [62]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性
这里是基本属性，而不是方法

In [63]:
x.ndim # 数组的位数

1

In [64]:
X.ndim

2

In [65]:
x.shape # 这里是小写

(10,)

In [66]:
X.shape

(3, 5)

In [67]:
x.size

10

In [68]:
X.size

15

### ``numpy.array`` 的数据访问

In [69]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x[0]

0

In [71]:
x[-1]

9

In [72]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
X[0][0] # 不建议！

0

In [74]:
X[(0,0)] # 推荐使用元组进行访问

0

In [75]:
X[0, 0]  # 对圆括号的省略

0

In [76]:
X[0, -1]

4

#### 切片操作

In [77]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
x[0:5] # 

array([0, 1, 2, 3, 4])

In [79]:
x[:5]

array([0, 1, 2, 3, 4])

In [80]:
x[5:]

array([5, 6, 7, 8, 9])

In [81]:
x[4:7]

array([4, 5, 6])

In [82]:
x[::2] # 与 range 的操作相似，第三个参数代表步长

array([0, 2, 4, 6, 8])

In [83]:
x[1::2]

array([1, 3, 5, 7, 9])

In [84]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [85]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
X[:2, :3] # ❤️ 前两行的前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [87]:
X[:2][:3] # 结果不一样，在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
X[:2] # ❤️ 返回前2个元素，在二维数组中，也就是前2et行 ❤️ 所以 axix 取0的时候，是以行为单位

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

如果在这个基础上进行[:3] ，python 会在**有两行的数组中，寻找前3行**，结果只能是两行，并没有对列进行截取。
==所以不要使用两个中括号进行切片==

In [90]:
X[:2][:3] 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
X[:2, ::2] # 1 访问前两行 2 对于每一行，步长为2的访问 ❤️ 这样就有一种根据『语义的先后顺序』进行切片

array([[0, 2, 4],
       [5, 7, 9]])

In [92]:
X[::-1, ::-1] # 先反转行，再反转列

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [93]:
X[0, :] #取第一行，注意得到的是一位数组

array([0, 1, 2, 3, 4])

In [94]:
X[:, 0] # 取第一列

array([ 0,  5, 10])

In [95]:
X = iris.data[:,:2] # 取所有行，前两列

NameError: name 'iris' is not defined

### Subarray of ``numpy.array``

In [96]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [97]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [98]:
X 

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

* 在 Python 中的切片操作，其实是付支出一个新的矩阵，所以不会影响之前的值
* 在 Numpy 中的切片操作，会『牵连』到原来的值
> 因为Numpy 是引用的调用，所以效率会很高

In [99]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [101]:
subX = X[:2, :3].copy() # ❤️ 硬复制

In [102]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [103]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [104]:
x.shape

(10,)

In [105]:
x.ndim

1

In [106]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [107]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
A = x.reshape((2, 5)) 
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
A = x.reshape(2, 5) # 可以省略这个小括号
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
x # reshape 操作虽然赋值给 A，但是并没有改变 x 自己的形状

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
B = x.reshape(1, 10) # 注意这里是二维矩阵,❤️吴恩达也提醒我们，尽量保持二维矩阵，不要使用一维矩阵
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [112]:
B.ndim

2

In [113]:
B.shape

(1, 10)

#### 对 reshape 的修改

In [121]:
B[0,0] = 999
B

array([[999,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [122]:
print(x)
print(B)

[999   1   2   3   4   5   6   7   8   9]
[[999   1   2   3   4   5   6   7   8   9]]


In [128]:
C = x.reshape(1,10).copy() ## 要通过硬复制来进行
C

array([[999,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [129]:
C[0,0]  = 888
print(C)
print(x)

[[888   1   2   3   4   5   6   7   8   9]]
[999   1   2   3   4   5   6   7   8   9]


In [130]:
x.reshape(-1, 10)

array([[999,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [131]:
x.reshape(10, -1)

array([[999],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [132]:
x.reshape(2, -1) # ❤️ -1 代表让电脑自动运算

array([[999,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [133]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)