## 03 测试我们的算法
![IMAGE](https://ws1.sinaimg.cn/large/006tKfTcly1fs39dv04zpj30oq0dajw6.jpg)


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [3]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [4]:
X = iris.data

In [5]:
y = iris.target

In [6]:
X.shape

(150, 4)

In [7]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [8]:
y # y是按照顺序的，我们要把它打乱

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

我们不能只打乱 X，要 x 和 y 一起配对打乱。
**小妙招**：我们打乱索引，原来的数据顺序不发生变化，我们用打乱的索引来提取数据。

In [9]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 38, 113,  30,  35,  87, 122,  10,   0, 119, 104,   1, 112,  82,
        90,   7,   5, 143,   9,  85,  98, 129, 118, 125,  62,  93,  21,
       117,  58, 111,  65, 147, 148,  15, 116, 103, 108,  96,  97,  73,
       136, 132, 127, 149, 115, 126,  44, 106, 121,  72, 109,  43, 145,
        60, 124,  32,  77,  91,  48,  33,  24, 130, 100,  29,  17,  66,
       135,  31,  68,  86,  88,  63,  28, 146,  12,   3,  39, 123,  50,
        61,  19, 138,  27,  34,  54,  70,  94,  46, 105,  11,  89,  49,
        16,  79, 140,  67,  23, 134,  18, 120, 102,  75, 139,  20,  74,
       131,  84, 142,  78,  36,  22,  51, 114,   2,  13,  99,   6, 144,
        92,  37,  25,  26,   4,  47,  64,  76,  80,  57,  81, 110,  41,
       133,  52, 141,  69,  53,  45,   8,  95, 137,  59,  42, 107,  55,
       101,  14,  56,  71,  83,  40, 128])

In [72]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [73]:
test_indexes = shuffled_indexes[:test_size] 
train_indexes = shuffled_indexes[test_size:]

In [74]:
X_train = X[train_indexes] #❤️ fancy indexing
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [75]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [76]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [83]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [84]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [85]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [86]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [87]:
y_predict

array([2, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0,
       1, 1, 2, 2, 0, 0, 1])

In [88]:
y_test

array([2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0,
       1, 1, 2, 2, 0, 0, 1])

In [90]:
sum(y_predict == y_test)

29

In [91]:
sum(y_predict == y_test) / len(y_test)

0.96666666666666667

#### sklearn中的train_test_split

In [92]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split>

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [94]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [95]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
