## 03 ``numpy.array`` 基础

In [1]:
import numpy

In [3]:
numpy.__version__ # 查看版本号

'1.13.3'

In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

### Python List的特点

In [3]:
L = [i for i in range(10)] # Python 的生成表达式，Comprehension
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [7]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

Python的List不要求存储同样的类型，**带来效率问题**。所以我们要引入 Python 中的 Array，只能存储一种类型的数据。

In [8]:
import array
arr = array.array('a', [i for i in range(10)])
arr

ValueError: bad typecode (must be b, B, u, h, H, i, I, l, L, q, Q, f or d)

In [9]:
import array
arr = array.array('i', [i for i in range(10)]) # 这里的 i 代表整形，后面是生成 array 的 list
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [12]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [13]:
arr[5] = 5.0

TypeError: integer argument expected, got float

``array``的缺点是没有将数据当做向量或者矩阵，不支持基本运算。

### ``numpy.array``

In [14]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5] = 100 # 和 Python list 相同的读取方法
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [17]:
nparr.dtype # 数组中到底存储着什么类型的数据

dtype('int64')

In [18]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr.dtype

dtype('int64')

In [20]:
nparr[5] = 3.14 # 浮点数自动进行截位！！！！
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [21]:
nparr2 = np.array([1, 2, 3.0]) # 大多数情况下都是 float64
nparr2.dtype

dtype('float64')