## 08 ``Numpy`` 中的聚合操作
聚合：把一组数据，编程一个数据

### sum

In [4]:
import numpy as np

np.random.seed(6)
L = np.random.random(100)
print(L)
sum(L)

[ 0.89286015  0.33197981  0.82122912  0.04169663  0.10765668  0.59505206
  0.52981736  0.41880743  0.33540785  0.62251943  0.43814143  0.73588211
  0.51803641  0.5788586   0.6453551   0.99022427  0.8198582   0.41320093
  0.87626766  0.82375943  0.05447451  0.71863724  0.80217056  0.73640664
  0.70913175  0.54093685  0.12482417  0.9576473   0.4032563   0.21695116
  0.71727585  0.99420744  0.25561406  0.67130943  0.59900591  0.71733215
  0.93734953  0.35180977  0.2536341   0.40247251  0.74651072  0.72407057
  0.4061078   0.98937985  0.45049928  0.37380843  0.70962861  0.08245855
  0.39837292  0.77088097  0.76475098  0.28385938  0.18954219  0.47125096
  0.33480604  0.73473504  0.18910712  0.33110407  0.84422842  0.61502403
  0.88526408  0.97655302  0.83690859  0.18082463  0.61841051  0.47610887
  0.40415665  0.74188369  0.82593329  0.68322983  0.13927161  0.70282506
  0.05883729  0.19266547  0.92479376  0.40510246  0.14829153  0.68228713
  0.16348875  0.64822524  0.25161414  0.0413755   0

52.884348235295143

In [5]:
np.sum(L)

52.884348235295143

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

82.8 ms ± 889 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
393 µs ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### min, max

In [8]:
np.min(big_array)

7.3731113547914617e-08

In [9]:
np.max(big_array)

0.99999987577570693

也可以使用面向对象的方式进行运算，但是 np.max()会有更多的函数

In [17]:
big_array.min()

7.3731113547914617e-08

In [18]:
big_array.max()

0.99999987577570693

In [19]:
big_array.sum()

499798.2737483863

### 多维度聚合

In [20]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.sum(X)

120

In [24]:
np.sum(X, axis=0) # 沿着每一行，（行的方向，其实是列）其实得到的是列的和

array([24, 28, 32, 36])

In [25]:
np.sum(X, axis=1) # 沿着每一列，得到的是行的和

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [26]:
np.prod(X) # 所元素的乘积

0

In [27]:
np.prod(X + 1) # 就不用担心整形溢出

20922789888000

In [28]:
np.mean(X)

7.5

In [29]:
np.median(X)

7.5

In [30]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v) #10 这个点是 outlier

3.2000000000000002

In [31]:
np.median(v)

2.0

In [32]:
big_array

array([ 0.5332846 ,  0.8058708 ,  0.26127326, ...,  0.15338565,
        0.27758776,  0.1643109 ])

In [33]:
np.percentile(big_array, q=50)

0.49954464886831851

In [34]:
np.median(big_array)

0.49954464886831851

In [35]:
np.percentile(big_array, q=100) # 最大值

0.99999987577570693

In [36]:
np.max(big_array)

0.99999987577570693

In [37]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

7.37311135479e-08
0.249338708168
0.499544648868
0.750157200231
0.999999875776


In [38]:
np.var(big_array)

0.083382032525981017

In [39]:
np.std(big_array)

0.28875947175111161

In [40]:
x = np.random.normal(0, 1, 1000000) # 100000个均值为0，标准差为1的数据

In [41]:
x

array([ 0.17132839,  1.10508323,  1.26805532, ..., -0.78005644,
       -0.67028342,  1.43522554])

In [42]:
np.mean(x) # 验证 x 的均值是不是0

2.6689832900840797e-05

In [43]:
np.std(x) # 验证 x 的表混差是不是1

0.99997440297057039