## 04 创建 ``numpy.array``

In [1]:
import numpy as np


### 一、``numpy.array``传入一个 python list

In [73]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 二、其他创建 ``numpy.array`` 的方法

#### ``zeros``

In [74]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [75]:
np.zeros(10).dtype # 默认创建的是 float

dtype('float64')

In [76]:
np.zeros(10, dtype=float)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [77]:
np.zeros((3, 5)) # 传入元组，创建矩阵，这里省略了第一个『shape=』

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [78]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ones

In [79]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
np.ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### full

In [81]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [82]:
np.full((3, 5), 666).dtype

dtype('int64')

In [83]:
np.full(fill_value=666, shape=(3, 5)) # 显示参数名的情况下，可以交换参数列表的顺序

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

#### arange

In [84]:
[i for i in range(0, 20, 2)] # ！❤️ 这个我老忘

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [85]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [86]:
[i for i in range(0, 1, 0.2)] # python 本身的的 stride 不可以为浮点数

TypeError: 'float' object cannot be interpreted as an integer

In [87]:
np.arange(0, 1, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [88]:
[i for i in range(0, 10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [89]:
np.arange(0, 10) # 省略步长，步长默认为1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
[i for i in range(10)] # 省略起始点，默认为0，同时省略了步长，默认为1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### linspace
这个很像 range 和 arange，但是有些区别
* 第一个参数：起始点
* 第二个参数：终止点，注意是***包含***的！！！
* 第三个参数：不是步长！包含起始点和终止点，一共生成多少个数字，并且构成等差数列

In [92]:
np.linspace(0, 20, 10) 

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [93]:
np.linspace(0, 20, 11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

In [94]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

#### random

##### randint

In [95]:
np.random.randint(0, 10)    # [0, 10)之间的随机数

2

In [96]:
np.random.randint(0, 10, 10) # 第三个参数，代表生产随机数的数量，并且返回一个 list ❤️

array([6, 8, 5, 8, 5, 1, 4, 8, 4, 3])

In [97]:
np.random.randint(0, 1, 10) # 第二个参数，其实是开区间，取不到1的

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
np.random.randint(0, 10, size=10) #  三个都是数字，会让人费解，❤️ 第三个参数最好写上名字

array([5, 4, 0, 0, 4, 6, 7, 8, 9, 2])

In [99]:
np.random.randint(0, 10, size=(3,5)) # size 也可以是 tuple，从而返回一个二维 list

array([[8, 1, 0, 8, 9],
       [2, 6, 9, 5, 9],
       [7, 2, 4, 2, 0]])

In [58]:
np.random.randint(10, size=(3,5))

array([[5, 8, 6, 7, 5],
       [1, 8, 0, 7, 8],
       [0, 7, 6, 5, 5]])

##### seed：通常用于调试

In [59]:
np.random.seed(666)

In [60]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [61]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

##### random 随机小数

In [62]:
np.random.random()

0.7315955468480113

In [63]:
np.random.random(size = (3,5))

array([[ 0.8578588 ,  0.76741234,  0.95323137,  0.29097383,  0.84778197],
       [ 0.3497619 ,  0.92389692,  0.29489453,  0.52438061,  0.94253896],
       [ 0.07473949,  0.27646251,  0.4675855 ,  0.31581532,  0.39016259]])

In [64]:
np.random.random((3,5))

array([[ 0.26832981,  0.75366384,  0.66673747,  0.87287954,  0.52109719],
       [ 0.75020425,  0.32940234,  0.29130197,  0.00103619,  0.6361797 ],
       [ 0.97933558,  0.91236279,  0.39925165,  0.40322917,  0.33454934]])

##### rand 

In [101]:
np.random.rand()

0.21328309514776278

In [104]:
np.random.rand(5)

array([ 0.44518764,  0.01584702,  0.99491381,  0.90632665,  0.05199571])

In [102]:
np.random.rand(3,5)

array([[ 0.56115445,  0.71657783,  0.7493205 ,  0.58624783,  0.54759891],
       [ 0.0817732 ,  0.40852941,  0.63205157,  0.12168885,  0.27480879],
       [ 0.07770505,  0.15726591,  0.14978044,  0.38535367,  0.70941476]])

In [103]:
np.random.rand((3,5))

TypeError: 'tuple' object cannot be interpreted as an integer

##### normal

In [105]:
np.random.normal()

0.005923528419531469

In [106]:
np.random.normal(10, 100)

13.866362543511563

In [67]:
np.random.normal?

In [68]:
np.random.normal(0, 1, (3, 5))

array([[ 0.57656584, -0.07019407,  0.91250436,  1.00470497,  0.41859929],
       [-1.52902454,  0.92487532,  0.18305429,  0.34543496, -0.8131543 ],
       [ 1.06325382,  0.25866385,  0.47285107,  1.0319698 , -0.16045655]])

`np.random.<TAB>` 查看random中的更多方法

In [69]:
np.random?

In [70]:
np.random.normal? # 在弹出的窗口查看文档

SyntaxError: invalid syntax (<ipython-input-70-05fde684e71b>, line 1)

In [71]:
help(np.random.normal) # 在 notebook 中显示文档

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [100]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]